# Generated by Django 4.2.5 on 2024-01-18 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wassenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PREGUNTAS_TIPO_CERT',
            fields=[
                ('id_preguntas', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_cert', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('enunciado', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('pregunta_guardado', models.CharField(max_length=150)),
                ('nombre_api_radica', models.CharField(max_length=255)),
                ('validaciones', models.TextField()),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SOLICITUD',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('id_tipo_producto', models.IntegerField()),
                ('id_vigencia', models.IntegerField()),
                ('id_formato_entrega', models.IntegerField()),
                ('id_radicado_panel', models.IntegerField()),
                ('cupon', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('pago', models.BooleanField(default=False)),
                ('valida_identidad', models.BooleanField(default=False)),
                ('terminos_pc', models.BooleanField(default=False)),
                ('municipio_token', models.CharField(max_length=255)),
                ('ciudad_token', models.CharField(max_length=255)),
                ('direccion_token', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='STATUS',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('tipo_doc', models.CharField(max_length=45)),
                ('numero_doc', models.CharField(max_length=45)),
                ('correo', models.EmailField(max_length=254)),
                ('verificacion_correo', models.BooleanField(default=False)),
                ('terminos', models.BooleanField(default=False)),
                ('politicas', models.BooleanField(default=False)),
                ('fecha_exp', models.DateField()),
                ('estado', models.BooleanField(max_length=50)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO_MOVIL',
            fields=[
                ('id_usuario_movil', models.AutoField(primary_key=True, serialize=False)),
                ('celular', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wassenger.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SOLICITUD_VALIDACION_IDE',
            fields=[
                ('id_solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wassenger.solicitud')),
                ('link', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO_SOLICITUD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
                ('id_usuario_movil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wassenger.USUARIO_MOVIL')),
            ],
        ),
        migrations.CreateModel(
            name='SOLICITUD_PAGOS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('refpago', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wassenger.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='SOLICITUD_DOCUMENTOS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_docu', models.IntegerField()),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wassenger.solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wassenger.usuario'),
        ),
        migrations.CreateModel(
            name='RESPUESTAS_USUARIO',
            fields=[
                ('id_respuestas', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_user', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wassenger.preguntas_tipo_cert')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wassenger.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='RESPUESTAS_TIPO_CERT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resp_enunciado', models.TextField()),
                ('estado', models.BooleanField(default=False)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualiza', models.DateTimeField(auto_now=True)),
                ('id_pregunta_tipo_cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wassenger.preguntas_tipo_cert')),
            ],
        ),
    ]
