# Generated by Django 4.2.5 on 2024-01-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wassenger', '0002_preguntas_tipo_cert_solicitud_status_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_movil',
            name='estado_solicitud',
            field=models.CharField(default=100),
        ),
        migrations.AddField(
            model_name='usuario_movil',
            name='id_device',
            field=models.CharField(default=100),
        ),
    ]
